steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/unified-auth-server:$SHORT_SHA', '.']

  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/unified-auth-server:$SHORT_SHA', 'gcr.io/$PROJECT_ID/unified-auth-server:latest']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/unified-auth-server:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/unified-auth-server:latest']

  # Deploy to Cloud Run
  # 重要: 既存の環境変数とシークレットを保持するため、--set-env-varsは使用しない
  # 新しい環境変数を追加する場合のみ --update-env-vars を使用すること
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'unified-auth-server'
      - '--image=gcr.io/$PROJECT_ID/unified-auth-server:$SHORT_SHA'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--memory=512Mi'
      - '--cpu=1'
      # タイムアウト設定: API Proxy Serverへのリクエストを含む全体の処理時間
      - '--timeout=300s'
      # 環境変数: API Proxy Serverへのリクエストタイムアウト（API Proxy Serverと統一）
      # 注: Cloud Runタイムアウト（300s）より短く設定してエラーハンドリングを可能にする
      - '--update-env-vars=PROXY_TIMEOUT_SECONDS=240'
      # 既存のシークレット設定を保持（--set-secrets は使用しない）

images:
  - 'gcr.io/$PROJECT_ID/unified-auth-server:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/unified-auth-server:latest'

# Timeout for the entire build (10 minutes)
timeout: 600s

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
